# Exercise 1.3

I treat all possible lines as 1D arrays, i.e. [1,1,1], and the 2D array as a collection of multiple 1D arrays.
To check for number of consecutive numbers in each array, a for loop is iterating through each element and checking its value. If the value is correct, a counter is incremented each time a consecutive correct value occurs. If an uncorrect value occurs, the counter is reset to zero. 

#### For the vertical arrays/lines, i simply use numpy.transpose() to transpose the array, and run the same function as described above.

#### For diagonals, a function is made to slice all forward and backward diagonal patterns into new arrays. Then the consecutive_vals() is used to check.

This method will work for 2D ndarrays of any size and is not limited to n-by-n matrices

In [30]:
import numpy as np

def consecutive_vals(arr, num):
    """This function takes an array and checks each row 
    for consecutive occurences of a selected value num"""
    
    record = 0
    counter = 0
    for i in arr:
        for j in i:
            if j == num:
                counter += 1
                record = max(record,counter)
            else:
                counter = 0
        counter = 0
    return record

def transf_all_diags(arr):
    """This function takes an array and converts all possible
    diagonals (forward and backward) and converts them into a 
    list of respective arrays"""
    
    diags = [arr[::-1,:].diagonal(i) for i in range(-arr.shape[0]+1,arr.shape[1])] 
    diags.extend((a.diagonal(i) for i in range(a.shape[1]-1,-a.shape[0],-1)))
    return diags

#### This short snippet creates a 2D-array of 5x5 with random integers from 0 to 1, and finds the longest pattern of ones by using the functions above:

In [43]:
n = 1

a = np.random.randint(2, size= (5,5))
print("Test array: \n----------\n", a, "\n----------")

diags = transf_all_diags(a)
print("Longest pattern of ", n, "-s: " , max(consecutive_vals(diags,n),consecutive_vals(a,n),consecutive_vals(a.transpose(),n)), "\n")

Test array: 
----------
 [[0 1 0 0 0]
 [1 1 1 0 1]
 [0 0 0 1 1]
 [1 0 0 0 1]
 [0 1 1 1 0]] 
----------
Longest pattern of  1 -s:  4 

