# Assignment 1 - Basic Python
Name: Eirik Wik Haug

------------------
# Problem 1

A simple implementation of rock/paper/scissor game. The function 
takes in two strings and compares them to find a winner. It raises an
error and calls the help() function if the wrong input is given.

In [57]:
def RoPaSc(player_1_hand, player_2_hand):
    """Takes two strings as input and prints the winner. Accepted input: rock / paper / scissor"""
    
    if (player_1_hand == "rock" or player_1_hand == "paper" or \
        player_1_hand == "scissor") and (player_2_hand == "rock"\
        or player_2_hand == "paper" or player_2_hand == "scissor"): 
            
        if player_1_hand == player_2_hand:
            print("Tie! Try again.")
        elif player_1_hand == "rock":
            if player_2_hand == "paper":
                print("Player 2: wins")
            else:
                print("Player 1: wins")
        elif player_1_hand == "paper":
            if player_2_hand == "scissor":
                print("Player 2: wins")
            else:
                print("Player 1: wins")
        elif player_1_hand == "scissor":
            if player_2_hand == "rock":
                print("Player 2: wins")
            else:
                print("Player 1: wins")
    else:
        print ("Wrong input, try again.\n")
        help(RoPaSc)

### Try the game

In [58]:
a = input("Player 1 hand: ")
b = input("Player 2 hand: ")
RoPaSc(a,b)

Player 1 hand: rock
Player 2 hand: scissor
Player 1: wins


--------------------
# Exercise 1.2

In [59]:
from string import ascii_letters

def cipher(txt, k):
    """Takes a string (txt) and translates every ASCII letter in it by k (int) steps"""
    n = ''
    for i in txt:
        if (i in ascii_letters):
            n = n+ascii_letters[(ascii_letters.index(i)+k)%len(ascii_letters)]
        else:
            n += i
    return n

def decipher(txt, k):
    """This function simply reverses the cipher function."""
    n = ''
    for i in txt:
        if (i in ascii_letters):
            n = n+ascii_letters[(ascii_letters.index(i)-k)%len(ascii_letters)]
        else:
            n += i
    return n

### Cipher and write to file

In [60]:
f = open('plain.txt','r').read()
birthyear = 1993
k = birthyear % 10

newfile = open("cipher.txt" ,'w').write(cipher(f,k))

print(cipher(f,k))

ZkB lv DL dwwudfwlqj vr pxfk dwwhqwlrq?
DL lv wkh qhz hohfwulflwB. Lw zloo wudqvirup hyhuB lqgxvwuB dqg fuhdwh kxjh hfrqrplf ydoxh. 
WhfkqrorjB olnh vxshuylvhg ohduqlqj lv dxwrpdwlrq rq vwhurlgv. 
Lw lv yhuB jrrg dw dxwrpdwlqj wdvnv dqg zloo kdyh dq lpsdfw rq hyhuB vhfwru iurp khdowkfduh wr pdqxidfwxulqj, orjlvwlfv dqg uhwdlo.


### Bonus: Decipher

In [61]:
print(decipher(open("cipher.txt",'r').read(),k))

Why is AI attracting so much attention?
AI is the new electricity. It will transform every industry and create huge economic value. 
Technology like supervised learning is automation on steroids. 
It is very good at automating tasks and will have an impact on every sector from healthcare to manufacturing, logistics and retail.


--------------------
# Exercise 1.3

I treat all possible lines as 1D arrays, i.e. [1,1,1], and the 2D array as a collection of multiple 1D arrays.
To check for number of consecutive numbers in each array, a for loop is iterating through each element and checking its value. If the value is correct, a counter is incremented each time a consecutive correct value occurs. If an uncorrect value occurs, the counter is reset to zero. 

#### For the vertical arrays/lines, i simply use numpy.transpose() to transpose the array, and run the same function as described above.

#### For diagonals, a function is made to slice all forward and backward diagonal patterns into new arrays. Then the consecutive_vals() is used to check.

This method will work for 2D ndarrays of any size and is not limited to n-by-n matrices

In [68]:
import numpy as np

def consecutive_vals(arr, num):
    """Takes a numpy array and checks each row for 
    consecutive occurences of a selected value num"""
    
    record = 0
    counter = 0
    for i in arr:
        for j in i:
            if j == num:
                counter += 1
                record = max(record,counter)
            else:
                counter = 0
        counter = 0
    return record

def transf_all_diags(arr):
    """Takes an array and converts all possible diagonals 
    (forward and backward) and converts them into a 
    list of respective arrays"""
    
    diags = [arr[::-1,:].diagonal(i) for i in range(-arr.shape[0]+1,arr.shape[1])] 
    diags.extend((a.diagonal(i) for i in range(a.shape[1]-1,-a.shape[0],-1)))
    return diags

#### This short snippet creates a 2D-array of 5x5 with random integers from 0 to 1, and finds the longest pattern of ones by using the functions above:

In [69]:
n = 1

a = np.random.randint(2, size= (5,5))
print("Test array: \n----------\n", a, "\n----------")

diags = transf_all_diags(a)
print("Longest pattern of ", n, "-s: " , max(consecutive_vals(diags,n),\
         consecutive_vals(a,n),consecutive_vals(a.transpose(),n)), "\n")

Test array: 
----------
 [[1 0 0 0 1]
 [1 0 1 1 0]
 [1 1 1 0 1]
 [1 0 1 1 0]
 [1 0 1 0 1]] 
----------
Longest pattern of  1 -s:  5 

